### ISSUE TITLE
Git clone failed

### ISSUE THREAD

**Issue by sprunk** [gajop/Scened-Core#105]
http://pastebin.com/gqYf04ju

Cloning into 'LuaUI/images/scenedit/resources'...
fatal: reference is not a tree: 56fb60d58943c1445cc52c83d6a950d62b5be3c3
Unable to checkout '56fb60d58943c1445cc52c83d6a950d62b5be3c3' in submodule path 'LuaUI/images/scenedit/resources'

**Comment by gajop** [comment]
Whoops. Forgot to push that commit...
Truthfully I think you'll run into a number of other issues before I release the next version (https://github.com/gajop/Scened-Core/milestones/0.5). You can still try it out and if you can give me any opinions or suggestions I might incorporate them, but I think it's fair to warn you of the instability of current git version.

Fixed with https://github.com/gajop/Scenario-Editor-Resources/commit/56fb60d58943c1445cc52c83d6a950d62b5be3c3
