### ISSUE TITLE
Terrain altitude bounds

### ISSUE THREAD

**Issue by Anarchid** [gajop/Scened-Core#86]
Currently, editing terrain in Scened in a way that violates pre-existing map extremes will result in a heightmap that respects new extremes.

Compiling such a map for distribution requires the author to know these new extremes, which are not easy to obtain without a special widget.

The terrain sculpting tools could instead have an option to limit the changes to be within the original extremes, or at least within minHeight -- maxHeight.

**Comment by gajop** [comment]
My plans on this are:
- Ignore any type of global extremes such as Spring.GetGroundExtremes or custom equivalents, as it should be possible to produce a usable set of new extremes from Scened itself.
- Provide a tool that will add/remove height limited to a specific value, similarly to how Unity's paint terrain works. I might also the current level & set tools utilize the same tool: so it's only one tool with a "strength" factor that would determine the speed of the transformation and with an ability to source the desired height from the map like level does.
- I might merge it all in a single tool (so we would have only height paint + smooth), but that will probably only happen on the GUI side due to certain optimizations -> this is already not trivial to optimize and adding new options isn't exactly making it easier.
